FROM python:3.11-alpine
LABEL likelion.web.backend.author="JunYoung Kim <hjklo0220@gmail.com>"


ARG APP_HOME=/app

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ${APP_HOME}

COPY ./script/start /start
RUN sed -i  's/\r$//g' /start
RUN chmod +x /start

CMD [ "/start" ]
