version: '3'

services:
  lion-app:
    container_name: lion-app-dc
    image: ${NCR_HOST}/lion-app:0.5
    volumes:
      - ./:/app
      - "lion-app-v:/var/www/html"
    ports:
      - "8000:8000"
    command: 
      - "/start"
    env_file:
      - ./prod.env

  nginx:
    container_name: lion-nginx-dc
    image: ${NCR_HOST}/lion-nginx:0.1
    volumes:
      - "lion-app-v:/var/www/html"
    ports:
      - "8888:80"

volumes:
  lion-app-v:

