version: '3'

services:
  lion-app:
    depends_on:
      - db
    container_name: lion-app-dc
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: "lion-app:0.5"
    volumes:
      - ./:/app
      - "lion-app-v:/var/www/html"
    ports:
      - "8000:8000"
    command: 
      - "/start"
    env_file:
      - ./.envs/local/django
      - ./.envs/local/server
      - ./.envs/local/db

  nginx:
    # restart: always
    depends_on:
      - lion-app
    container_name: lion-nginx-dc
    build: 
      context: .
      dockerfile: Dockerfile.nginx_ubuntu
    image: lion-nginx
    volumes:
      - "lion-app-v:/var/www/html"
    ports:
      - "8888:80"
    env_file:
      - ./.envs/local/server

  db:
    container_name: lion-postgres-dc
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - ./.envs/local/db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  lion-app-v:
  postgres-data:

