version: '3'

services:
  lion-app:
    depends_on:
      - db
    container_name: lion-app-test
    build: 
      context: .
      dockerfile: ./Dockerfile

    env_file:
      - ./.envs/local/django
      - ./.envs/local/server
      - ./.envs/local/db

  db:
    container_name: db-test
    image: postgres:15
    ports:
      - 54321:5432
    env_file:
      - ./.envs/local/db


