version: '3'

services:
  lion-app:
    container_name: lion-app-dc
    # build: 
    #   context: .
    #   dockerfile: ./Dockerfile
    image: "${NCR_HOST}lion-app"
    volumes:
      - ~/.aws:/root/.aws:ro # ro: read only
      - ./:/app
      - "lion-app-v:/var/www/html"
    ports:
      - "8000:8000"
    command: 
      - "/start"
    env_file:
      - ./.envs/prod/django
      - ./.envs/prod/server
      - ./.envs/prod/db
    environment:
      - AWS_SECRET_NAME=like/lion/prod

  nginx:
    depends_on:
      - lion-app
    container_name: lion-nginx-dc
    build: 
      context: .
      dockerfile: Dockerfile.nginx_ubuntu
    image: lion-nginx
    volumes:
      - "lion-app-v:/var/www/html"
    ports:
      - "8888:80"
    env_file:
      - ./.envs/prod/server


volumes:
  lion-app-v:

