name: CD Staging server

on:
    push:
        branches:
          - 'main'
        paths:
          - '.github/workflow/CD.yml'
          - '**.py'
          - 'requirements.txt'
          - 'docker-compose.prod.yml'
          - 'Dockerfile'
# on:
#     workflow_dispatch:

env:
    IMAGE: ${{ vars.NCR_REGISTRY }}/lion-app
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/lion-app:latest


jobs:
    build-push:
        name: build-push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Get current timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"
  
            - name: bulid and export
              uses: docker/build-push-action@v4
              with:
                  context: .
                  tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                  push: true

        outputs:
            output1: ${{ steps.timestamp.outputs.timestamp }}

    
    deploy-staging:
        needs: build-push
        name: deploy to staging
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: server access
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.STAGE_HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
                docker login ${{ vars.NCR_REGISTRY }} \
                -u ${{ secrets.NCR_ACCESS_KEY }} -p ${{ secrets.NCR_SECRET_KEY }}
                docker pull ${{ env.IMAGE_TAG }}
                docker stop lion-app && docker rm lion-app
                docker run -p 8000:8000 -d \
                -v ~/.aws:/root/.aws:ro \
                --env-file /home/lion/devops6th/.env \
                --name lion-app \
                devops6th-cr.kr.ncr.ntruss.com/lion-app:latest
