name: CD using Docker Image


# build image
# push image to ncr
# pull image from ncr
# run new container with new image

on:
    push:
        branches:
          - 'main'
# on:
#     workflow_dispatch:

env:
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/lion-app:latest


jobs:
    build-push:
        name: build-push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY }}
                password: ${{ secrets.NCR_SECRET_KEY }}
  
            - name: bulid and export
              uses: docker/build-push-action@v4
              with:
                  context: .
                  tags: ${{ env.IMAGE_TAG }}
                  push: true
    
    pull-run:
        needs: build-push
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: server access
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
                cd devops6th
                git pull
                docker login ${{ vars.NCR_REGISTRY }} \
                -u ${{ secrets.NCR_ACCESS_KEY }} -p ${{ secrets.NCR_SECRET_KEY }}
                docker pull ${{ env.IMAGE_TAG }}
                docker stop lion-app && docker rm lion-app
                docker run -p 8000:8000 -d \
                -v ~/.aws:/root/.aws:ro \
                --env-file .envs/prod/django \
                --env-file .envs/prod/db \
                --env-file .envs/prod/server \
                --name lion-app \
                devops6th-cr.kr.ncr.ntruss.com/lion-app:latest \
                /start

        - name: echo IMAGE_TAG
          run: echo $IMAGE_TAG
