
name: lesson1

on:
    pull_request:
        types: [opened]
    push:
        branches:
          - 'main'

jobs:
    test:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: echo "This event is ${{github.event_name}}"
            #   run: echo "This event is $GITHUB_EVENT_NAME"
            - name: echo github context
              run: echo "${{github.repository}}"
            - name: listfiles
              run: ls -al
    
    lion-app-build:
        name: lion-app build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: lion-app build 
            #   working-directory: lion_app
              run: docker build --tag lion-app .

    docker-images:
        needs: lion-app-build
        name: docker images
        runs-on: ubuntu-latest
        steps:
            - name: docker images
              run: docker images lion-app


    # docker-compose-build:
    #     name: docker compose build
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: docker compose build
    #           run: docker-compose build

              