
name: lesson1

on:
    pull_request:
        types: [opened]
    push:
        branches:
          - 'main'

jobs:
    test:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: echo "This event is ${{github.event_name}}"
            - name: echo github context
              run: echo "${{github.repository}}"
            - name: listfiles
              run: ls -al
    
    lion-app-build:
        name: lion-app build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            # - name: lion-app build 
            #   run: docker build --tag lion-app .
            - name: set up docker buildx
              uses: docker/setup-buildx-action@v2

            - name: bulid and export
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: lion-app:latest
                outputs: type=docker, dest=/tmp/lion-app.tar
            
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: lion-app
                path: /tmp/lion-app.tar
            
            - name: docker images
              run: |
                docker load --input /tmp/lion-app.tar
                docker images

    docker-images:
        if: ${{ always() }}
        needs: lion-app-build
        name: docker images
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: lion-app
                path: /tmp

            - name: docker images
              run: |
                docker load --input /tmp/lion-app.tar
                docker images lion-app


              