name: CD using Docker Image


# build image
# push image to ncr
# pull image from ncr
# run new container with new image

on:
    push:
        branches:
          - 'main'
# on:
#     workflow_dispatch:

jobs:
    build-push:
        name: build-push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ secrets.NCR_HOST }}
                username: ${{ secrets.NCR_ACCESS_KEY }}
                password: ${{ secrets.NCR_SECRET_KEY }}
  
            - name: bulid and export
              uses: docker/build-push-action@v4
              with:
                  context: .
                  tags: ${{ secrets.NCR_HOST }}/lion-app:latest
                  push: true
                  
                
