
name: lesson1

on:
    pull_request:
        types: [opened]
    push:
        branches:
          - 'main'

jobs:
    test:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: echo "This event is ${{github.event_name}}"
            #   run: echo "This event is $GITHUB_EVENT_NAME"


