name: SSH test

on:
    push:
        branches:
          - 'main'

jobs:
    deploy:
        name: deploy-server
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        # 서버 접속
        - name: ssh
          run: |
            ssh-keyscan -t rsa {{ secrets.USERNAME }} >> ~/.ssh/known_hosts
            sshpass -p ${{ secrets.PASSWORD }} ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }}
            cd devops6th
            git pull
            docker compose -f docker-compos.prod.yml restart
