name: SSH test

on:
    push:
        branches:
          - 'main'

jobs:
    deploy:
        name: deploy-server
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Configure SSH
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
                HostName $SSH_HOST
                User $SSH_USER
                IdentityFile ~/.ssh/staging.key
                StrictHostKeyChecking no
            END
            env:
            SSH_USER: ${{ secrets.USERNAME }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
            SSH_HOST: ${{ secrets.HOST }}
    
        - name: git pull and restart
          run: |
            cd lion_app
            git pull
            docker compose -f docker-compos.prod.yml restart
